/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/Laptop.glb 
*/

import React, { useRef, useLayoutEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/Laptop.glb");
  const { actions, names } = useAnimations(animations, group);

  // useLayoutEffect(() => {
  //   names.forEach((animation) => {
  //     actions?.[animation]?.play();
  //   });
  // }, [actions, names]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Cube007"
          position={[-0.022, -0.009, -0.016]}
          scale={[0.167, 0.005, 0.152]}
        >
          <mesh
            name="Cube005_1"
            geometry={nodes.Cube005_1.geometry}
            material={materials["Material.043"]}
          />
          <mesh
            name="Cube005_2"
            geometry={nodes.Cube005_2.geometry}
            material={materials["Material.044"]}
          />
          <mesh
            name="Cube005_3"
            geometry={nodes.Cube005_3.geometry}
            material={materials["Material.008"]}
          />
        </group>
        <group
          name="Cube002"
          position={[-0.022, -0.009, -0.016]}
          rotation={[1.712, 0, 0]}
          scale={[0.168, 0.005, 0.153]}
        >
          <mesh
            name="Cube009"
            geometry={nodes.Cube009.geometry}
            material={materials["Material.040"]}
          />
          <mesh
            name="Cube009_1"
            geometry={nodes.Cube009_1.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Cube009_2"
            geometry={nodes.Cube009_2.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <group
          name="Cube004"
          position={[-0.022, -0.009, -0.016]}
          rotation={[1.712, 0, 0]}
          scale={[0.168, 0.005, 0.153]}
        >
          <mesh
            name="Cube004_1"
            geometry={nodes.Cube004_1.geometry}
            material={materials["Material.040"]}
          />
          <mesh
            name="Cube004_2"
            geometry={nodes.Cube004_2.geometry}
            material={materials["Material.041"]}
          />
          <mesh
            name="Cube004_3"
            geometry={nodes.Cube004_3.geometry}
            material={materials["Material.042"]}
          />
        </group>
        <group
          name="Cube005"
          position={[-0.022, -0.009, -0.016]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.011, 0.001, 0.009]}
        >
          <mesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Cube006_1"
            geometry={nodes.Cube006_1.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials["Material.001"]}
          position={[-0.022, -0.009, -0.016]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.006, -0.003, -0.004]}
        />
        <mesh
          name="Cube035"
          geometry={nodes.Cube035.geometry}
          material={materials["Material.036"]}
          position={[-0.022, -0.009, -0.016]}
          scale={[0.167, 0.005, 0.152]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Laptop.glb");
